### ISSUE TITLE
Mach-O Linker Errors

### ISSUE THREAD

**Issue by BrettyWhite** [lauraskelton/simple-share#1]
Hi Laura, Thanks for putting this together. When compiling I'm running into the issues below. If you know what they are or how to make them go away I'd be appreciative!

Thanks!
1. Undefined symbols for architecture i386:
   "_OBJC_CLASS_$_SimpleShare", referenced from:
       objc-class-ref in MyItemsViewController.o
       objc-class-ref in AppDelegate.o
   ld: symbol(s) not found for architecture i386
2. clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by lauraskelton** [comment]
Hi Brett, Thanks for letting me know! I fixed the way the SimpleShare folder is referenced, and it should build correctly now. Please let me know if it doesn't.

Best,
Laura
